version: "3.9"
services:
  mongodb:
    build:
      context: .
      dockerfile: mongo.Dockerfile
    networks:
      - bridges
    ports:
      - "27017:27017"
    env_file:
      - metabase/config/mongo_exemple.env

  postgres:
    image: postgres:latest
    networks:
      - bridges
    ports:
      - "5432:5432"
    env_file:
      - metabase/config/postgres_exemple.env

  metabase:
    build:
      context: .
      dockerfile: metabase.Dockerfile
    networks:
      - bridges
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - postgres
    env_file:
      - metabase/config/metabase_database_exemple.env

  # python-app:
  #   build:
  #     context: .
  #     dockerfile: python.Dockerfile
  #   networks:
  #     - bridges
  #   depends_on:
  #     - metabase

networks:
  bridges:
    driver: bridge