name: Build Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt
        pip install sphinx
        pip install sphinx_autodoc_typehints
        sudo apt-get install doxygen

    - name: Run Doxygen
      run: |
        cd docs
        doxygen Doxyfile

    - name: Run Sphinx
      run: |
        cd docs
        sphinx-apidoc -f -o . ../src/
        make html
